import type { ChatMessage } from "@/hooks/use-bond-ai-chat";

interface TranscriptOptions {
  brandName: string;
  aiName: string;
  conversationType: string;
  messages: ChatMessage[];
  extractedData: Record<string, unknown>;
  riskProfile: { level: string; score: number; flags: string[]; summary?: string } | null;
  issuedBondNumber: string | null;
}

function formatKey(key: string): string {
  return key
    .replace(/([A-Z])/g, " $1")
    .replace(/^./, (c) => c.toUpperCase())
    .trim();
}

function formatValue(key: string, val: unknown): string {
  if (val === null || val === undefined) return "—";
  if (typeof val === "number" && key.toLowerCase().includes("amount"))
    return `$${val.toLocaleString()}`;
  return String(val);
}

function flattenObject(
  obj: Record<string, unknown>,
  prefix = ""
): Array<[string, unknown]> {
  const result: Array<[string, unknown]> = [];
  for (const [key, val] of Object.entries(obj)) {
    const fullKey = prefix ? `${prefix}.${key}` : key;
    if (val !== null && val !== undefined && typeof val === "object" && !Array.isArray(val)) {
      result.push(...flattenObject(val as Record<string, unknown>, fullKey));
    } else if (Array.isArray(val)) {
      result.push([fullKey, val.join(", ")]);
    } else {
      result.push([fullKey, val]);
    }
  }
  return result;
}

function conversationTypeLabel(type: string): string {
  const map: Record<string, string> = {
    new_application: "New Bond Application",
    renewal: "Bond Renewal",
    endorsement: "Endorsement / Amendment",
    referral: "Client Referral",
  };
  return map[type] || type;
}

function pad(n: number) {
  return String(n).padStart(2, "0");
}

function ts() {
  const d = new Date();
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}`;
}

export function generateTranscriptText(opts: TranscriptOptions): string {
  const {
    brandName,
    aiName,
    conversationType,
    messages,
    extractedData,
    riskProfile,
    issuedBondNumber,
  } = opts;

  const divider = "═".repeat(60);
  const thinDivider = "─".repeat(60);
  const lines: string[] = [];

  lines.push(divider);
  lines.push(`  ${brandName} — ${aiName} Conversation Transcript`);
  lines.push(divider);
  lines.push("");
  lines.push(`  Type:       ${conversationTypeLabel(conversationType)}`);
  lines.push(`  Exported:   ${ts()}`);
  if (issuedBondNumber) {
    lines.push(`  Bond #:     ${issuedBondNumber}`);
  }
  lines.push("");

  lines.push(thinDivider);
  lines.push("  APPLICATION DATA");
  lines.push(thinDivider);
  lines.push("");

  const dataEntries = flattenObject(extractedData).filter(
    ([, v]) => v !== null && v !== undefined
  );

  if (dataEntries.length === 0) {
    lines.push("  No application data collected during this session.");
  } else {
    const maxKeyLen = Math.max(
      ...dataEntries.map(([k]) => formatKey(k).length)
    );
    for (const [key, val] of dataEntries) {
      const label = formatKey(key).padEnd(maxKeyLen + 2);
      lines.push(`  ${label}${formatValue(key, val)}`);
    }
  }
  lines.push("");

  lines.push(thinDivider);
  lines.push("  RISK ASSESSMENT");
  lines.push(thinDivider);
  lines.push("");

  if (riskProfile) {
    lines.push(
      `  Risk Level:   ${riskProfile.level.toUpperCase()}`
    );
    lines.push(`  Risk Score:   ${riskProfile.score} / 100`);
    if (riskProfile.summary) {
      lines.push(`  Summary:      ${riskProfile.summary}`);
    }
    if (riskProfile.flags.length > 0) {
      lines.push("");
      lines.push("  Attention Areas:");
      for (const flag of riskProfile.flags) {
        lines.push(`    • ${flag}`);
      }
    }
  } else {
    lines.push("  Risk assessment was not completed during this session.");
  }
  lines.push("");

  lines.push(thinDivider);
  lines.push("  CONVERSATION HISTORY");
  lines.push(thinDivider);
  lines.push("");

  const visibleMessages = messages.filter((m) => m.content && !m.isAgentSwitch);

  for (const msg of visibleMessages) {
    const sender =
      msg.role === "user"
        ? "You"
        : msg.agentDisplayName || aiName;
    const prefix = msg.role === "user" ? "▶" : "◀";
    lines.push(`  ${prefix}  ${sender}`);

    const wrapped = wordWrap(msg.content, 56);
    for (const wLine of wrapped) {
      lines.push(`     ${wLine}`);
    }
    lines.push("");
  }

  lines.push(divider);
  lines.push(
    `  This transcript was automatically generated by ${brandName}.`
  );
  lines.push("  It may be used for audit, compliance, or personal records.");
  lines.push(divider);

  return lines.join("\n");
}

function wordWrap(text: string, maxWidth: number): string[] {
  const result: string[] = [];
  const paragraphs = text.split("\n");
  for (const para of paragraphs) {
    if (para.trim() === "") {
      result.push("");
      continue;
    }
    const words = para.split(" ");
    let currentLine = "";
    for (const word of words) {
      if (currentLine.length + word.length + 1 > maxWidth && currentLine.length > 0) {
        result.push(currentLine);
        currentLine = word;
      } else {
        currentLine = currentLine ? currentLine + " " + word : word;
      }
    }
    if (currentLine) result.push(currentLine);
  }
  return result;
}

export function downloadTranscript(opts: TranscriptOptions) {
  const text = generateTranscriptText(opts);
  const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);

  const d = new Date();
  const dateStr = `${d.getFullYear()}${pad(d.getMonth() + 1)}${pad(d.getDate())}`;
  const typeSlug = opts.conversationType.replace(/_/g, "-");
  const filename = `bondassist-transcript-${typeSlug}-${dateStr}.txt`;

  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
